kvcache-ai/Mooncake

- dependencies.sh
- mooncake-transfer-engine/example/memory_pool.cpp
- mooncake-transfer-engine/include/transfer_engine.h
- mooncake-transfer-engine/include/transfer_metadata.h
- mooncake-transfer-engine/include/transport/tcp_transport/tcp_transport.h
- mooncake-transfer-engine/include/transport/transport.h
- mooncake-transfer-engine/src/transfer_metadata.cpp
- mooncake-transfer-engine/src/transport/tcp_transport/tcp_transport.cpp
add missing `std::` to string, otherwise the build will failed.
my env:
```
cmake version 3.31.1
CMake suite maintained and supported by Kitware (kitware.com/cmake).
```
```
gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
> [Bugfix] cpp std::string

- doc/en/vllm-integration-v0.2-nightly.md
Doc update to explain the option of metadata server backend for vllm integration.
> [Doc] Add metadata server backend explanation.

- mooncake-transfer-engine/include/transport/rdma_transport/rdma_endpoint.h
- mooncake-transfer-engine/src/transport/rdma_transport/endpoint_store.cpp
- mooncake-transfer-engine/src/transport/rdma_transport/rdma_transport.cpp
1. fix typo in ./mooncake-transfer-engine/src/transport/rdma_transport/endpoint_store.cpp 
> FIFOEndpointStore -> SIEVEEndpointStore 
2. fix rdma device selection when retry_count != 0, we should get correct device_id from priority_matrix
> [Bugfix] fix typos and fix rdma device selection when retry_count != 0

- README.md
- doc/en/vllm-integration-v0.2-nightly.md
Since [PR 10884](https://github.com/vllm-project/vllm/pull/10884) has been merged, this PR updates the integration state of Mooncake Transfer Engine with vLLM.
> [Doc] Update the integration state of Mooncake Transfer Engine with vLLM.

- doc/en/transfer-engine.md
- doc/zh/transfer-engine.md
- mooncake-transfer-engine/include/topology.h
- mooncake-transfer-engine/src/topology.cpp
- mooncake-transfer-engine/tests/CMakeLists.txt
- mooncake-transfer-engine/tests/topology_test.cpp
This PR adds automatic topology discovery for CPU/GPU and RDMA devices.
> [TransferEngine] Add topology discovery

- mooncake-integration/vllm/vllm_adaptor.cpp
Mooncake supports vllm integration with etcd/redis/http as metadata service. You can change it in mooncake.json 
```
{
"prefill_url": "192.168.0.137:13003",
"decode_url": "192.168.0.139:13003",
"metadata_server": "192.168.0.139:2379", # you can add protocol prefix like "etcd://", "redis://" or "http://"
"protocol": "rdma", # if you use protocol prefix in metadata_server, this field is ignored
"device_name": "erdma_0"
}
```
> [Transfer Engine] fix metadata server connection string builder in vllm intergation

- mooncake-p2p-store/src/p2pstore/transfer_engine.go
- mooncake-transfer-engine/include/transfer_engine_c.h
Need `C.free` to free memory, since `C.CString` will invoke C.malloc to allocate a new memory.
Also, add API convention to make free safety.
> [p2pstore] fix memory leaking in cgo.

- mooncake-transfer-engine/src/transport/rdma_transport/rdma_context.cpp
- mooncake-transfer-engine/src/transport/rdma_transport/worker_pool.cpp
1. Correct the count of slice_queue_, although it has no adverse effects
2. The overlap check in rdma_transport is repeat with checkOverlap in TransferEngine::registerLocalMemory which is better
> [TransferEngine] Correct the count of slice_quque_ in rdma/worker_pool, remove the repeated check for overlap

- mooncake-p2p-store/src/p2pstore/transfer_engine.go
- mooncake-transfer-engine/include/transfer_engine_c.h
- mooncake-transfer-engine/rust/src/transfer_engine.rs
- mooncake-transfer-engine/src/transfer_engine_c.cpp
Add the `auto_discover` parameter to transfer_engine_c, according to the changes in PR #73.
cc @alogfans @doujiang24
> [TransferEngine] fix: add auto_discover in transfer_engine_c

- doc/en/transfer-engine.md
- doc/zh/transfer-engine.md
- mooncake-transfer-engine/include/common.h
- mooncake-transfer-engine/include/memory_location.h
- mooncake-transfer-engine/src/memory_location.cpp
- mooncake-transfer-engine/src/topology.cpp
- mooncake-transfer-engine/src/transport/rdma_transport/rdma_transport.cpp
- mooncake-transfer-engine/tests/CMakeLists.txt
- mooncake-transfer-engine/tests/memory_location_test.cpp
- mooncake-transfer-engine/tests/rdma_transport_test.cpp
- mooncake-transfer-engine/tests/topology_test.cpp
1. try best to recognize the cpu numa node for now,
2. use all nic when failed to get the numa node,
3. will support cuda memory in the feature.
> [TransferEngine] feature: registerLocalMemory support the "*" location.

- Dockerfile
1. Use Alibaba Cloud AC2 as the Base Image
2. Base on Ubuntu22.04 with builtin pytorch and cuda driver
> [Build] feature: add dockerfile to enable use Mooncake in Docker

- mooncake-transfer-engine/include/transport/transport.h
- mooncake-transfer-engine/src/multi_transport.cpp
- mooncake-transfer-engine/src/transport/nvmeof_transport/nvmeof_transport.cpp
- mooncake-transfer-engine/src/transport/rdma_transport/rdma_transport.cpp
- mooncake-transfer-engine/src/transport/tcp_transport/tcp_transport.cpp
Since the slices are solely utilized for counting purposes, replace them with counters to eliminate memory overhead
> [TransferEngine]chore: replace slices vector with slice counter

- mooncake-transfer-engine/include/transfer_engine.h
- mooncake-transfer-engine/src/transfer_engine.cpp
- Introduced `std::shared_mutex` to protect `local_memory_regions_` from concurrent access.
- Added `std::shared_lock<std::shared_mutex>` for read-only operations:
- `checkOverlap()` now acquires a shared lock to allow concurrent reads.
- Added `std::unique_lock<std::shared_mutex>` for write operations.
- Updated `installTransport()` with a comment clarifying that locking is not needed, as it is only executed during initialization.
- Ensured that memory region modifications occur within a locked context to prevent race conditions.
Future considerations:
- If `installTransport()` is later used in a concurrent context, a `std::shared_lock<std::shared_mutex>` should be introduced.
Fixes: #107
> [Bugfix] Add shared and unique lock for local_memory_regions_ (#107)

- mooncake-transfer-engine/example/transfer_engine_bench.cpp
Add gflags of report in transfer_engine_benchmark: `report_unit` and `report_precision`.
> [TransferEngine] BenchMark: Introduce report gflags for enhanced configurability

- CMakeLists.txt
- mooncake-transfer-engine/example/transfer_engine_bench.cpp
- mooncake-transfer-engine/src/CMakeLists.txt
- mooncake-transfer-engine/src/multi_transport.cpp
- mooncake-transfer-engine/src/transport/CMakeLists.txt
- mooncake-transfer-engine/src/transport/nvmeof_transport/cufile_context.cpp
- mooncake-transfer-engine/tests/rdma_transport_test.cpp
- mooncake-transfer-engine/tests/rdma_transport_test2.cpp
- mooncake-transfer-engine/tests/tcp_transport_test.cpp
The current nvmeof transport only support CUDA 12, we can keep it disabled for older CUDA versions, as a workaround now.
Also, rename the `gpu:` prefix to `cuda:`, to align with doc & topology.cpp.
> [TransferEngine] feature: introduce USE_NVMEOF to enable NVMe-oF separately.

- mooncake-transfer-engine/include/common.h
- mooncake-transfer-engine/include/transport/rdma_transport/rdma_transport.h
- mooncake-transfer-engine/src/transport/rdma_transport/rdma_transport.cpp
- mooncake-transfer-engine/tests/memory_location_test.cpp
- mooncake-transfer-engine/tests/topology_test.cpp
- mooncake-transfer-engine/tests/transport_uint_test.cpp
Suppress gtest compile warning and fix some trivial bugs.
> [TransferEngine] Suppress gtest type cast compile warning and fix some trivial bugs

- mooncake-transfer-engine/src/transport/rdma_transport/rdma_context.cpp
In the function `RdmaContext::getBestGidIndex`, we select the first GID with an IPv4-mapped address without considering the GID type.
Since the connection is now TCP-based, it requires the type of GID to be RoCEv2. 
Selecting a RoCEv1 GID will result in an error due to the poor connection:
```
E0219 16:52:31.208603 273373 worker_pool.cpp:281] Worker: Process failed for slice (opcode: 0, source_addr: 0x7f593802c000, length: 4096, dest_addr: 140622732378112, local_nic: mlx5_bond_0, peer_nic: x.x.x.x:12345@mlx5_bond_2, dest_rkey: 1568428, retry_cnt: 0): transport retry counter exceeded
E0219 16:52:31.208797 273373 worker_pool.cpp:281] Worker: Process failed for slice (opcode: 0, source_addr: 0x7f593800c000, length: 4096, dest_addr: 140622732247040, local_nic: mlx5_bond_0, peer_nic: …
```
> [Bugfix] fix the gid choice of IB device: only choose IBV_GID_TYPE_ROCE_V2 now

- mooncake-transfer-engine/example/transfer_engine_bench.cpp
Compilation fails when using clang as the toolchain, with the following error:
```
error: variable-sized object may not be initialized
void *addr[NR_SOCKETS] = {nullptr};
```
> Fix compilation error with clang toolchain

- mooncake-p2p-store/build.sh
- mooncake-p2p-store/src/p2pstore/go.mod
- mooncake-p2p-store/src/p2pstore/transfer_engine.go
- mooncake-transfer-engine/example/http-metadata-server/go.mod
Fix golang vulnerabilities in P2P store. Update the version of `golang.org/x/net`.
> [FIX] golang vulnerabilities in P2P store

- mooncake-integration/vllm/distributed_object_store.cpp
Reduced an unnecessary memory copy
> [MooncakeStore] Enhance performance in DistributedObjectStore::get

- mooncake-transfer-engine/example/transfer_engine_bench.cpp
Added signal handlers for SIGINT (Ctrl+C) and SIGTERM (kill <PID>).
Now, the program exits gracefully, releasing allocated resources before termination.
> [Fix]: Handle SIGINT & SIGTERM for graceful shutdown

- .github/workflows/ci.yml
- mooncake-integration/CMakeLists.txt
- Added `$ORIGIN/lib_so` as a runtime library search path (RUNPATH) to `mooncake_vllm_adaptor`, which has lower precedence than `LD_LIBRARY_PATH`.
- Fixed the issue where the etcd dependency (`libetcd-cpp-api.so`) was hardcoded into the mooncake-wheel.
> [Fix] Fix issues with run path and etcd dependency integration

- doc/en/vllm-integration-v1.md
Since the PR about `MooncakeStoreConnector` has been merged into the main branch of vLLM, we need to update the doc. vLLM activates v1 by default, so we need to add the env param VLLM_USE_V1=0.
> [Doc] Update vllm MooncakeStore integration doc 

- .github/workflows/release.yaml
- dependencies.sh
The default search order now starts with RPATH, followed by LD_LIBRARY_PATH.
> [Enhance] Add an RPATH that takes precedence over LD_LIBRARY_PATH and other paths in the wheel package

- mooncake-transfer-engine/include/transport/transport.h
- mooncake-transfer-engine/src/transport/rdma_transport/rdma_transport.cpp
New slices are created/allocated in submitTransfer() and submitTransferTask(), but they're not freed after transfer, which results in memory leak as processing transfer tasks. I'm seeing memory accumulated in longterm stress testing.
Fix it by deleting such slices in WorkerPool::performPollCq(), after marking slice as done (either failed or success).
> [TransferEngine] fix: avoid leaking Slice memory in RDMA transport

- mooncake-transfer-engine/include/transfer_engine.h
- mooncake-transfer-engine/src/transport/rdma_transport/rdma_endpoint.cpp
- mooncake-transfer-engine/src/transport/rdma_transport/rdma_transport.cpp
- mooncake-transfer-engine/src/transport/rdma_transport/worker_pool.cpp
- mooncake-transfer-engine/tests/CMakeLists.txt
- mooncake-transfer-engine/tests/rdma_loopback_test.cpp
... which is faster than memcpy in many cases
> [TransferEngine] Use RDMA transport to transfer data in local process rapidly

- mooncake-common/etcd/etcd_wrapper.go
- mooncake-transfer-engine/src/transfer_metadata_plugin.cpp
- Change `errMsg` params to `​**​C.char` in Go wrapper
- Add `&` operator in C++ callsites
- Fixes: error message propagation
> [Bugfix] mooncake-common: fix error pointer handling in CGO interfaces​​

- mooncake-integration/transfer_engine/transfer_engine_py.cpp
- mooncake-integration/transfer_engine/transfer_engine_py.h
- mooncake-transfer-engine/include/memory_location.h
- mooncake-transfer-engine/include/transfer_engine.h
- mooncake-transfer-engine/src/memory_location.cpp
- mooncake-transfer-engine/src/topology.cpp
- mooncake-transfer-engine/src/transport/rdma_transport/rdma_transport.cpp
- mooncake-transfer-engine/tests/memory_location_test.cpp
- mooncake-transfer-engine/tests/rdma_transport_test.cpp
- mooncake-transfer-engine/tests/topology_test.cpp
To enable fully auto detection of topology in Transfer Engine, just leave the device name empty in the Python interface.
> [Feature] support auto-detect topo for both GPUs and CPUs

- doc/en/sglang-integration-v1.md
The configuration file requirement has been removed since [PR 5460](https://github.com/sgl-project/sglang/pull/5460). There is no need to prepare the _mooncake.json_ file anymore.
> [Doc] Remove mooncake configuration file requirement

- mooncake-integration/transfer_engine/transfer_engine_py.cpp
- mooncake-transfer-engine/include/topology.h
- mooncake-transfer-engine/include/transfer_engine.h
- mooncake-transfer-engine/src/topology.cpp
- mooncake-transfer-engine/src/transfer_engine.cpp
- mooncake-transfer-engine/src/transport/rdma_transport/rdma_transport.cpp
When user specify the `device_name` in the init function, the auto topology detection algorithm will use only the device listed. If a device failed to open, it will be removed from the topology internally.
> [TransferEngine] Add whitelist to the auto topology detection

- mooncake-integration/CMakeLists.txt
- mooncake-store/tests/stress_workload_test.cpp
There is a build error in stress_workload_test.cpp. It looks like that gflags header is missing.
> [FIX] Fix build error of stress_workload_test.cpp

- CMakeLists.txt
- doc/en/build.md
- doc/zh/build.md
- mooncake-transfer-engine/CMakeLists.txt
In case we want to build transfer engine only, enhance transfer engine CMakeLists.txt to support building transfer engine indepedently. e.g.
```bash
cd mooncake-transfer-engine
mkdir build
cd build
cmake .. -DUSE_REDIS=OFF -DBUILD_UNIT_TESTS=OFF
make -j
```
Also introduce new build options, BUILD_UNIT_TESTS and BUILD_EXAMPLES, and add them to doc.
> [TransferEngine] build: support build transfer engine independently

- mooncake-transfer-engine/include/transport/transport.h
We found that `new (slice) Slice()` introduces memory leak. After allocating slice objects, user code will reinitialize the structure. So it's safe to remove this line.
> [TransferEngine] Fix memory leak problem in ThreadLocalSliceCache

- mooncake-common/etcd/etcd_wrapper.go
Remove trailing white spaces, indent correctly.
> [Chore] mooncake-common: format go code properly

- dependencies.sh
dependench.sh installs Go even if the version is already correct.
```bash
=== Installing Go 1.23.8 ===
Go 1.23.8 is already installed. Skipping...
Downloading Go 1.23.8...
go1.23.8.linux-amd64.tar.gz                               100%[====================================================================================================================================>]  70.25M  82.4MB/s    in 0.9s    
Installing Go 1.23.8...
✓ Go 1.23.8 installed successfully
```
> fix: skip Go install if version matches in depensench.sh

- mooncake-integration/store/store_py.cpp
vllm log
```
E0425 04:55:27.502805 51451 store_py.cpp:588] Query failed for key: vllm@/disc/data1/deepseek/DeepSeek-R1-AWQ@8@0@103afe94368f4bdd0bcf93d06adefb7acbddec01b91c469c13bfd21430ed4e24 with error: UNKNOWN_ERROR
```
> [FIX] Return null while OBJECT_NOT_FOUND

- mooncake-transfer-engine/CMakeLists.txt
- mooncake-transfer-engine/include/transfer_engine.h
- mooncake-transfer-engine/src/transfer_engine.cpp
When using transfer engine as a standalone library, the application itself may have metrics framework, so metrics in transfer engine is not needed.
Add WITH_METRICS build option to control metrics, which can be turned off with -DWITH_METRICS=OFF. We could also avoid depending on yalantinglibs in transfer engine.
> [TransferEngine] add option to enable metrics or not

- mooncake-integration/CMakeLists.txt
- mooncake-store/CMakeLists.txt
- mooncake-transfer-engine/CMakeLists.txt
- mooncake-transfer-engine/include/config.h
- mooncake-transfer-engine/include/topology.h
- mooncake-transfer-engine/include/transfer_metadata.h
- mooncake-transfer-engine/src/topology.cpp
- mooncake-transfer-engine/src/transfer_metadata.cpp
- mooncake-transfer-engine/src/transfer_metadata_plugin.cpp
RPM based distros like RHEL or Fedora, jsoncpp header files are at /usr/include, while deb based distros like debian or ubuntu such header files are at /usr/include/jsoncpp
To support building on both distro families, let's include <json/json.h> instead of <jsoncpp/json/json.h> and add /usr/include/jsoncpp to include path as well.
> [TransferEngine] build: support on rpm based distros

- CMakeLists.txt
- mooncake-common/etcd/CMakeLists.txt
In this pr, two main issues have been fixed. 
1. Firstly, when building with google-glog 0.7.0, it was necessary to add `add_compile_definitions(GLOG_USE_GLOG_EXPORT)`. Same as this isse: https://github.com/mhx/dwarfs/issues/201.
2. Secondly, when build_etcd_wrapper was being built using make, the shell used was /bin/sh, which led to the inability to find `go` command. Because the previous installation script installed `go` under the .bashrc file.
> [Bugfix] Fixed potential issues that may occur during the CMake build process

- mooncake-store/include/master_client.h
- mooncake-store/include/master_metric_manager.h
- mooncake-store/include/master_service.h
- mooncake-store/include/rpc_service.h
- mooncake-store/proto/master.proto
- mooncake-store/src/client.cpp
- mooncake-store/src/master.cpp
- mooncake-store/src/master_client.cpp
- mooncake-store/src/master_metric_manager.cpp
- mooncake-store/src/master_service.cpp
As the existing implementation of `isExist` leverage to the `getReplicationList`, there are some affects.
1. The `getReplicationList` return all replications info to the client, but client never used it, it is a waste behavior and harmful for performance.
2. The exists operations are considered as `get replication` operation, so the metrics can be confused, and the gc after 1s is triggered by the `get replication` operation too.
So I add a new true `isExist` rpc between `client` and `master`. 
1. Run vllm + lmcache + mooncake store
- start mooncake master
```shell
mooncake_master -max_threads 64 -v=1 -metrics_port=8081
```
- prepare lmcache.yaml
```yaml
chunk_size: 256
local_device: "cpu"
remote_url: "mooncakestore:/localhost:50051/"
remote_serde: "naive"
pipelined_backend: False …
```
> [store|proto]: Add ExistKey rpc as implementation of IsExist

- .gitmodules
It will be more friendly when people forked in a private repo instead of github.
> gitmodules: use full path instead of relative path.

- mooncake-wheel/mooncake/mooncake_config.py
- mooncake-wheel/tests/test_mooncake_config.py
- scripts/test_installation.sh
There are 3 existing place need the `MooncakeConfig`, so I propose to abstract it into the whl file which supplied by mooncake.
- https://github.com/vllm-project/vllm/blob/376786fac1fc50e8d788a39a91fa28d1709ad48b/vllm/distributed/kv_transfer/kv_lookup_buffer/mooncake_store.py#L29
- https://github.com/LMCache/LMCache/blob/702fba782d0fa4940c31f970e1aef481cdb9010a/lmcache/experimental/storage_backend/connector/mooncakestore_connector.py#L40
- https://github.com/kvcache-ai/Mooncake/pull/328/commits/deb89b2075926adc5f74d1adbd4e2acccbc47a71#diff-fd59ce035f5508afc145b7b7c8d4def42344b2df64445e31d6283aadfebc0789R12
> feat(Mooncake Integration): Supply a MooncakeConfig into whl file

- Dockerfile
This pr has optimized the building process of the Dockerfile and fixed the potential issues in the original building method:
1. In the original method of using `wget https://github.com/kvcache-ai/Mooncake/archive/refs/heads/main.zip`, after downloading and unzipping, the project will lack the `.git` file. As a result, during the `bash dependencies.sh` stage, the submodule cannot be found.
2. The `RUN` commands have been combined and the cache has been deleted to reduce the size of the image.
3. It is now allowed to directly start the mooncake_master_server through the container.
> [Build] feature: start the Mooncake master server through Docker

- mooncake-store/src/master_service.cpp
```
I0512 23:15:16.652259  1527 allocator.cpp:16] buf_handle_deallocated segment_name=192.168.100.219:12986 size=11
I0512 23:15:16.652276  1527 master_service.cpp:339] action=remove_all_objects, removed_count=1, total_freed_size=11
I0512 23:15:16.652279  1527 scoped_vlog_timer.h:77] RemoveAll response: {"removed_count":1}, latency=64us
I0512 23:15:26.011116  1521 rpc_service.h:78] Master Metrics: Storage: -11.00 B / 75.02 GB (-0.0%) | Keys: 0 | Requests (Success/Total): Put=2/2, Get=0/0, Exist=0/0, Del=0/0, DelAll=1/1
```
- start master
```console
/usr/local/lib/python3.12/dist-packages/mooncake/mooncake_master -max_threads 64 -v=1 -metrics_port=8081
```
- start mooncake-store-service
```
python3 /usr/local/lib/python3.12/dist-packages/mooncake/mooncake_store_service.py …
```
> fix(master): Fix negative storage size metrics after removeAll

- mooncake-transfer-engine/include/config.h
- mooncake-transfer-engine/include/transport/rdma_transport/rdma_context.h
- mooncake-transfer-engine/src/config.cpp
- mooncake-transfer-engine/src/transport/rdma_transport/rdma_context.cpp
Now when global_segment_size in mooncake.json is larger than device's max_mr_size, the registration will failed. But the application will still enter a fake normal state, like LMCache. Reduce the buffer length to the maximum value allowed by the device and issue a warning if encountering such scenario.
> [Transfer Engine] Check the buffer size before register

- mooncake-common/common.cmake
- mooncake-integration/CMakeLists.txt
- mooncake-store/CMakeLists.txt
- mooncake-store/src/CMakeLists.txt
- mooncake-transfer-engine/CMakeLists.txt
- mooncake-transfer-engine/src/CMakeLists.txt
- mooncake-transfer-engine/src/transport/CMakeLists.txt
- mooncake-transfer-engine/src/transport/rdma_transport/CMakeLists.txt
- mooncake-transfer-engine/src/transport/tcp_transport/CMakeLists.txt
Previously, we included headers like glog/logging.h without first checking
if the required packages were installed. This caused build failures at
compilation time rather than at configuration time.
This change implements proper dependency handling by:
- Adding find_package() calls for glog and yanlantinglibs
- Ensuring configuration fails early if dependencies are missing
- Improving error reporting for missing requirements
Users will now get clear configuration-time errors instead of confusing
compilation failures when dependencies aren't satisfied.
Signed-off-by: Kefu Chai <tchaikov@gmail.com>
> [Build] Call find_package() before using external deps

- mooncake-store/include/master_service.h
- mooncake-store/src/master_service.cpp
- mooncake-store/tests/master_service_test.cpp
Although `UnmountSegement` remove the specified segment from buffer_allocator_manager, but the related metadata of objects still exists.
Although `MetadataAccessor` will remove these invalid key in the constructor, but it will still leak if the related keys do not be accessed any more.
So the safe way is remove the related keys in the UnmountSegement function.
- It would be better to collect the `UnmountSegement` request and execute it async.
> fix(store): the metadata leak after umount segment

- doc/en/lmcacheV1-deployment.md
See https://github.com/kvcache-ai/Mooncake/issues/378#:~:text=assist%20users%20in-,integrating,-with%20LMCache.
This doc introduces how to integrate Mooncake Store to LMCache V1.
> [Doc] Add document for integrating Mooncake Store to LMCache V1

- benchmarks/xypd_benchmarks/vllm-benchmarks/benchmarks.sh
Remove the "=" to get PID of vllm thread.
> [Bugfix] Fix PID retrieval when destroying the vLLM thread in the vllm benchmark demo

- mooncake-transfer-engine/src/transport/rdma_transport/rdma_endpoint.cpp
In the previous implementation, we missed to update the `cq_outstanding` variable, which may block further operations b y other endpoints
> [TE FIX] Updating the outstanding work request counting when closing a QP

- mooncake-integration/transfer_engine/transfer_engine_py.cpp
- mooncake-transfer-engine/example/transfer_engine_bench_with_retry.cpp
- mooncake-transfer-engine/src/transfer_metadata.cpp
- mooncake-transfer-engine/src/transfer_metadata_dump.cpp
- mooncake-transfer-engine/src/transport/rdma_transport/worker_pool.cpp
The previous code may cause inconsistency (e.g., handling connection failure or timeouts)
> Remove duplicated code between transferSync[Read|Write] and transferSync

- mooncake-integration/transfer_engine/transfer_engine_py.cpp
- mooncake-integration/transfer_engine/transfer_engine_py.h
- mooncake-transfer-engine/include/transport/transport.h
- mooncake-transfer-engine/src/multi_transport.cpp
- mooncake-transfer-engine/src/transport/nvmeof_transport/nvmeof_transport.cpp
- mooncake-transfer-engine/src/transport/rdma_transport/rdma_endpoint.cpp
- mooncake-transfer-engine/src/transport/rdma_transport/rdma_transport.cpp
- mooncake-transfer-engine/src/transport/rdma_transport/worker_pool.cpp
- mooncake-transfer-engine/src/transport/tcp_transport/tcp_transport.cpp
Now supports two kinds of timeout:
1. end-to-end timeout in transferSync, 60 seconds by default. This can be changed using env var `MC_TRANSFER_TIMEOUT`.
2. data transfer timeout, 10 seconds by default. This is similar to RDMA's hardware timeout notification. However, in some environments, the QP will be destroyed so that we cannot poll for notification.
> [TransferEngine] Update software-based timeout mechanism

- mooncake-store/include/master_metric_manager.h
- mooncake-store/src/allocator.cpp
- mooncake-store/src/master_metric_manager.cpp
- mooncake-store/src/master_service.cpp
- mooncake-store/tests/CMakeLists.txt
- mooncake-store/tests/master_metrics_test.cpp
1. The eviction-related metrics are calculated but do not add to the output string.
2. When unmounting a segment, keys are removed, but the corresponding metrics do not change.
3. Adjust the position of some eviction metrics code blocks to make code ordering consistent.
> [Fix] Store Metrics-related Bugs

- doc/en/mooncake-store-preview.md
- doc/zh/mooncake-store-preview.md
- docs/source/design/mooncake-store-preview.md
- mooncake-store/include/master_service.h
- mooncake-store/include/rpc_service.h
- mooncake-store/include/types.h
- mooncake-store/src/master.cpp
- mooncake-store/src/master_service.cpp
- Introduce a new flag for mooncake master
- Default to 1.0 to keep consistent with original behavior.
- Support to custom to a value between 0 ~ 1, e.g. 0.8 mean while the space used ratio achieved to 0.8 will trigger batch eviction.
- Start master
```
/usr/local/lib/python3.12/dist-packages/mooncake/mooncake_master -v=1 -max_threads 64  -eviction_ratio=0.3 -eviction_high_watermark_ratio=0.7
```
- Prepare mooncake.json
```json
{
"local_hostname": "localhost",
"metadata_server": "etcd://localhost:2379",
"protocol": "rdma",
"device_name": "mlx5_bond_6",
"global_segment_size": 167772160,
"master_server_address": "localhost:50051"
}
```
- MOONCAKE_CONFIG_PATH=../mooncake.json python3 /usr/local/lib/python3.12/dist-packages/mooncake/mooncake_store_service.py
- Put 15MiB file into …
> followup(#374)(master): Add high watermark ratio flag to avoid trigger eviction until put failed

- mooncake-store/include/client.h
- mooncake-store/include/master_client.h
- mooncake-store/include/master_service.h
- mooncake-store/include/rpc_service.h
- mooncake-store/proto/master.proto
- mooncake-store/src/client.cpp
- mooncake-store/src/master.cpp
- mooncake-store/src/master_client.cpp
- mooncake-store/src/master_service.cpp
- mooncake-store/tests/client_integration_test.cpp
This PR supports to put/get a batch of data in order to reduce master rpc call. It provides BatchPutStart, BatchPutEnd, BatchPutRevode and BatchGet APIs. I am still working on Python Store Batch API and will post it soon.   Related RFC: https://github.com/kvcache-ai/Mooncake/issues/380
> [MooncakeStore] support batch api

- mooncake-store/include/master_service.h
- mooncake-store/include/rpc_service.h
- mooncake-store/src/master_service.cpp
For detailed discuss, please check this  [RFC](https://github.com/kvcache-ai/Mooncake/issues/381)
Here are some examples:
```
12638900504727518832_12489051952825107803
17704606561907141142_15702553452409431093
...
{
"segment_name_": "192.168.1.105:16384",
"size_": 65536,
"buffer_address_": 139903195893632,
"status_": 1
}
```
> [MooncakeStore]Provide cache aware interface for scheduler

- doc/en/build.md
- doc/en/transfer-engine.md
- doc/zh/build.md
- doc/zh/transfer-engine.md
refer to issue: https://github.com/kvcache-ai/Mooncake/issues/474
added additional requirements about common.cmake
And fixed the cmake version to 3.20
> fixed etcd and cmake version issues

- mooncake-integration/store/store_py.cpp
- mooncake-store/include/client.h
- mooncake-store/include/transfer_task.h
- mooncake-store/src/CMakeLists.txt
- mooncake-store/src/client.cpp
- mooncake-store/src/transfer_task.cpp
- mooncake-store/tests/CMakeLists.txt
- mooncake-store/tests/client_integration_test.cpp
- mooncake-store/tests/transfer_task_test.cpp
- mooncake-transfer-engine/include/transport/rdma_transport/rdma_transport.h
This PR introduces a comprehensive abstraction layer for client-side data transmission.
1. **Async Memcpy**: Foundation for making memory copy operations asynchronous
2. **Advanced Batching**: Enhanced batch processing 
```cpp
// Before: Direct transfer engine calls
engine_.submitTransfer(batch_id, requests);
// After: Abstracted through TransferSubmitter
auto future = transfer_submitter_->submit(handles, slices, op_code);
ErrorCode result = future->get();
```
This abstraction enables several planned optimizations:
1. **Thread Pool Integration**: Ready for introducing thread pools for parallel processing
2. **Performance Monitoring**: Built-in hooks for transfer performance metrics
> feat(client): Abstract client-side data transmission for async and batch optimization

- doc/en/transfer-engine.md
- doc/zh/transfer-engine.md
- mooncake-transfer-engine/src/transfer_metadata_plugin.cpp
Hi, this PR implements configurable Redis authentication and database selection through environment variables:
1. Redis Password Authentication
* Added support for `MC_REDIS_PASSWORD` environment variable
* When set: 
1. Authentication command (AUTH) automatically sent during connection; 
2. Uses provided password value;
* When unset:
1. No authentication attempted; 
2. Maintains default Redis connection behavior;
2. Database Index Selection
* Added support for `MC_REDIS_DB_INDEX` environment variable
* When set: 
1. SELECT command automatically executed to switch databases; 
2. Uses provided integer index value (e.g., `MC_REDIS_DB_INDEX`=3)
* When unset: 
1. No SELECT command sent; 
2. Default database (index 0) remains active;
> [TransferEngine] Add Redis password authentication and DB selection via environment variables

- mooncake-transfer-engine/include/transport/transport.h
- mooncake-transfer-engine/src/multi_transport.cpp
- mooncake-transfer-engine/src/transfer_engine.cpp
- mooncake-transfer-engine/src/transfer_engine_c.cpp
1: warning: comparison of integer expressions of different signedness: ‘long int’ and ‘long unsigned int’
` if (ts > 0 && current_ts > ts &&current_ts - ts > kPacketDeliveryTimeout)`
2:warning: unused variable ‘ret’ [-Wunused-variable] `int ret = metadata_->sendNotify(desc->name, notify_msg, peer_desc);`
3: warning: unused variable ‘rc’ [-Wunused-variable] ` int rc = submitTransfer(engine, batch_id, entries, count)`
> [TransferEngine]: fix compilation warning

- mooncake-transfer-engine/src/transfer_metadata_plugin.cpp
This PR attempts to fix race condition in `SocketHandShakePlugin` destructor.
The `SocketHandShakePlugin` destructor had a race condition where it would close the listening socket (closeListen()) before stopping the listener thread. This could cause undefined behavior if the listener thread was still running and attempting to use the socket that had just been closed. In the following screenshot `accept` fails because it is using a closed listening socket.
The original destructor order was:
1. `closeListen()` - closes the socket
2. Stop listener thread and join
This created a race condition because the listener thread's main loop continuously calls `accept(listen_fd_, ...)` and other socket operations, which could fail or cause undefined behavior if the socket was closed while the thread …
> [TransferEngine] bugfix: ensure proper socket closure in destructor

- mooncake-transfer-engine/example/transfer_engine_bench.cpp
- mooncake-transfer-engine/src/transfer_engine.cpp
To use MNNVL:
- Ensure that you build the package WITH USE_MNNVL parameter
- Your platform does not install RDMA; or setting environment variable MC_FORCE_MNNVL.
> [TransferEngine] Add support to force MNNVL transport by MC_FORCE_MNNVL

- mooncake-store/src/transfer_task.cpp
- mooncake-store/tests/CMakeLists.txt
- mooncake-store/tests/stress_workload_test.cpp
- Set `MC_STORE_MEMCPY` default to `false` in `transfer_task.cpp`
- RDMA performance is more stable than memcpy operations
- Rewrite `stress_workload_test.cpp` as standalone benchmark
- Add separate throughput calculations for PUT and GET operations
- Include comprehensive performance metrics:
- Latency percentiles (P50, P90, P95, P99)
- Operation-specific throughput (ops/sec)
- Data throughput (MB/s) for PUT and GET separately
- Add configurable parameters for threads, operations, buffer sizes
> Disable memcpy by default and improve stress workload test

- doc/en/mooncake-store-preview.md
- doc/zh/mooncake-store-preview.md
In the python interfaces of mooncake store, the initAll() is a C++ function, after its converted to python with pybind, its name should be init_all()
> fixed initall function

- mooncake-integration/store/store_py.cpp
- mooncake-integration/store/store_py.h
- mooncake-store/src/client.cpp
- mooncake-wheel/tests/test_distributed_object_store.py
- mooncake-wheel/tests/test_ssd_offload_in_evict.py
- scripts/run_tests.sh
- **Added Python interface for `unregister_buffer`**:  
- Currently, the Python interface only provides the `register_buffer` method without a corresponding `unregister` method. To address this, we have added the `unregister` interface, which brings two key benefits:  
- For upper-layer applications, it allows undoing registered buffers when needed, maintaining operational consistency.  
- For certain tests, repeated `register_buffer` calls may cause buffer space overlap, leading to test failures. The `unregister` interface helps avoid this issue.  
- **Re-enabled SSD offload in evict test**:  
- The test was temporarily disabled due to issues caused by a previous PR that turned off some persistent operations. It has now been re-enabled but will only run when testing SSD offload …
> [Store] Add ungister_buffer api for Store

- mooncake-integration/store/store_py.cpp
- mooncake-integration/store/store_py.h
1. release slice correctly, put batch uses RAII slice, get batch still need release slices manually
2. obligatory acquiring gil before accessing py object, compatible with later version of Python
> fix: correctly cleanup local buffer allocation

- mooncake-transfer-engine/src/memory_location.cpp
The `getMemoryLocation` function in `memory_location.cpp` has a potential integer overflow bug when processing large memory allocations (i.e., with a `len` greater than 2GB).
In the original implementation, the total number of pages `n` and the loop counter `i` are both of type `int`. When calculating page addresses inside the loops, the expression `i * pagesize` is performed using integer arithmetic.
```cpp
// Buggy lines in the original code
pages[i] = (void *)((char *)aligned_start + i * pagesize);
// and
new_start_addr = alignPage((uint64_t)start) + i * pagesize;
```
If the total memory size `len` is large enough to make `i * pagesize` exceed `INT_MAX`, the multiplication will overflow before being added to the `uint64_t` base address. This results in an incorrect address calculation …
> fix(memory): Prevent integer overflow in getMemoryLocation for large memory regions

- mooncake-integration/store/store_py.cpp
- mooncake-integration/store/store_py.h
Python users can write:
```python
buf = store.get_buffer("key")
store.close()
```
`store.close()` calls `client_buffer_allocator_.reset()`, destroying the
underlying `SimpleAllocator` immediately.  
Any remaining `SliceBuffer` instances still point into that allocator; when
their destructors invoke `allocator_->deallocate()` the `this` pointer is
nullptr, leading to a segmentation fault.
1. **Lifetime management**
* Convert `DistributedObjectStore::client_buffer_allocator_` from
`std::unique_ptr` to `std::shared_ptr`.
* Create it with `std::make_shared` inside `setup()`.
* `SliceBuffer` captures its own `std::shared_ptr<SimpleAllocator>` so the
allocator stays alive until every `SliceBuffer` is destroyed.
2. **Code clean-up**
* Add a defensive nullptr check in `SliceBuffer` destructor. …
> [BugFix] Prevent SIGSEGV when SliceBuffer is destroyed after DistributedObjectStore::close()

- mooncake-transfer-engine/include/common.h
- mooncake-transfer-engine/src/transfer_engine.cpp
- mooncake-transfer-engine/src/transfer_metadata_plugin.cpp
- mooncake-transfer-engine/tests/CMakeLists.txt
- mooncake-transfer-engine/tests/common_test.cpp
PR [kvcache-ai/Mooncake#479](https://github.com/kvcache-ai/Mooncake/pull/479) introduced IPv6 support in Mooncake. However, there were still a few places that required additional changes for full IPv6 compatibility.
This PR addresses those remaining issues.
> [TransferEngine] Add IPv6 support [2]

- mooncake-integration/transfer_engine/transfer_engine_py.cpp
Fix the compilation warnings below
>  /Mooncake/mooncake-integration/transfer_engine/transfer_engine_py.cpp: In member function 'int TransferEnginePy::batchRegisterMemory(std::vector<long unsigned int>, std::vector<long unsigned int>)':
/Mooncake/mooncake-integration/transfer_engine/transfer_engine_py.cpp:590:23: warning: comparison of integer expressions of different signedness: 'int' and 'long unsigned int' [-Wsign-compare]
590 |     for (int i = 0; i < batch_size; i ++ ) {
|                     ~~^~~~~~~~~~~~
> /Mooncake/mooncake-integration/transfer_engine/transfer_engine_py.cpp: In member function 'int TransferEnginePy::batchUnregisterMemory(std::vector<long unsigned int>)':
/Mooncake/mooncake-integration/transfer_engine/transfer_engine_py.cpp:600:23: warning: comparison of integer …
> [TransferEngine] fix the compilation warnings

- .github/workflows/ci.yml
- doc/en/mooncake-store-preview.md
- doc/zh/mooncake-store-preview.md
- docs/source/design/mooncake-store-preview.md
- mooncake-store/include/types.h
- mooncake-store/tests/client_integration_test.cpp
- mooncake-wheel/tests/test_distributed_object_store.py
- mooncake-wheel/tests/test_put_get_tensor.py
- mooncake-wheel/tests/test_ssd_offload_in_evict.py
- scripts/run_tests.sh
Since we now support batch get operations, a single request can transfer a large amount of data. Therefore, we have relaxed the default KV TTL value. At the same time, to avoid increasing the execution time of unit tests, we’ve applied a special override for this value specifically in the unit test configuration.
> [Store] Enlarge the Default KV TTL

- mooncake-transfer-engine/example/transfer_engine_bench.cpp
- mooncake-transfer-engine/example/transfer_engine_bench_with_retry.cpp
- mooncake-transfer-engine/tests/rdma_transport_test.cpp
This PR enhances the mooncake transfer engine benchmark to support multi-GPU configurations and improves memory allocation logic for better performance demonstration.
- Added support for using all available GPUs: When gpu_id=-1, the benchmark now automatically detects and utilizes all available GPUs
- Dynamic buffer allocation: The number of buffers now scales with the number of GPUs when using VRAM
- Enhanced logging: Added detailed logging for GPU memory allocation to aid in debugging and monitoring
- Single GPU: --gpu_id=0 (existing behavior)
- Multi-GPU: --gpu_id=-1 (**new feature - uses all available GPUs**)
The changes maintain full backward compatibility with existing single-GPU configurations while enabling multi-GPU scenarios for enhanced performance testing. I have test the …
> feat(transfer_engine_bench): Add multi-GPU support 

- mooncake-common/common.cmake
- mooncake-common/tests/CMakeLists.txt
On my ubuntu 20.04, there is a link error for missing pthread link flag when building
`mooncake-common/tests/CMakeFiles/default_config_test.dir/default_config_test.cpp.o`
Add a link flag in cmake files to fix it.
> [CI/Build] Mooncake-common/common.cmake: Add link flag of pthread

- docs/source/troubleshooting/troubleshooting.md
Add troubleshooting section for RDMA memory registration failures with diagnostic commands and solutions.
> docs: add RDMA memory registration troubleshooting guide

- mooncake-transfer-engine/src/transfer_engine.cpp
Currently, TE (TransferEngine) does not validate whether the memory size is zero during memory registration. This can lead to initialization appearing successful, but later data transfers failing.
Specifically, if `TransferEngine::registerLocalMemory` is called twice within the same process—once with size 0 and once with a non-zero size, with the `location` set as `*`, both memory regions will be registered under the same name. During data transfer, `TransferMetadata::decodeSegmentDesc` will be invoked. Even if only the non-zero-sized memory region is accessed, the logic will still validate both buffers. The zero-sized buffer will fail the validation checks, ultimately causing the data transfer to fail.
> [BugFix] Forbid Register Zero Size Memory

- scripts/build_wheel.sh
Fix https://github.com/kvcache-ai/Mooncake/pull/502#issuecomment-3179098704
> [TransferEngine] exclude packaging ascend precompiled libraries

- mooncake-transfer-engine/src/transport/tcp_transport/tcp_transport.cpp
Currently when using CUDA with TCP it assumes that we allocated a new buffer in line 152, it's not always the case and we can free memory that doesn't belong to us causing a segfault later
> Fix deleting buffer that doesn't belong to us

- mooncake-store/include/client.h
- mooncake-store/include/client_metric.h
- mooncake-store/include/master_client.h
- mooncake-store/include/transfer_task.h
- mooncake-store/src/CMakeLists.txt
- mooncake-store/src/client.cpp
- mooncake-store/src/client_metric.cpp
- mooncake-store/src/master_client.cpp
- mooncake-store/src/transfer_task.cpp
- mooncake-store/tests/CMakeLists.txt
- mooncake-store/tests/client_metrics_test.cpp
In this PR, we introduce client side support for both transfer and RPC-related metrics.
We provide interface support: Prometheus-style and human-readable formats. Additionally, we've implemented a background thread for metric printing (disabled by default).
```
I20250812 17:07:51.023622 117228 client.cpp:1417] Client Metrics Report:
Client Metrics Summary
=== Transfer Metrics Summary ===
Total Read: 5.00 MB
Total Write: 5.00 MB
=== Latency Summary (microseconds) ===
Get: count=103, p95<250μs, max<15000μs
Put: count=4, p95<1500μs, max<15000μs
Batch Get: count=1, p95<125μs, max<15000μs
Batch Put: count=3, p95<5000μs, max<20000μs
=== RPC Metrics Summary ===
GetReplicaList: count=104, p95<150μs, max<200μs
PutStart: count=5, p95<250μs, max<250μs
PutEnd: count=4, p95<200μs, max<1500μs
Remove: …
```
> feat(client): Add client-side metrics for transfer and RPC operations

- mooncake-store/include/offset_allocator/offset_allocator.hpp
- mooncake-store/include/serializer.h
- mooncake-store/include/types.h
- mooncake-store/src/offset_allocator.cpp
- mooncake-store/tests/CMakeLists.txt
- mooncake-store/tests/master_metrics_test.cpp
- mooncake-store/tests/offset_allocator_test.cpp
- mooncake-store/tests/serializer_test.cpp
This feature will be used for persisting master KV metadata. The serialize and deserialize methods of OffsetAllocator are implemented as templates; otherwise, offset_allocator.h would need to directly or indirectly include type.h, which would result in circular dependencies and compilation failure.
> [Store] Serialize/Deserialize Offset Allocator

- docs/source/index.md
- docs/source/performance/allocator_benchmark_result.md
Move the benchmark result to the docs as suggested by @stmatengss  in #641
> [Doc] Allocator Performance

- mooncake-common/include/default_config.h
- mooncake-common/src/default_config.cpp
As titled. Please refer to https://github.com/jbeder/yaml-cpp/issues/554 and its subsequent follow up solution in https://github.com/Jmeyer1292/robot_cal_tools/issues/102. 
Thank you! Please let me know if there is anything else I need to fill out for good PR etiquette.
> [Bugfix] YAML CPP has inline impl in header file which will cause linking error

- mooncake-transfer-engine/src/transfer_engine_c.cpp
Fix the bug in nixl bench. Using strncpy without handling the boundary. Occasionally, incorrect characters appear at the end. Causing errors in string matching for nixl. So use strcpy instead. The size of char[] is allocated as the string size +1. So use strcpy is fine.
> fix nixl bench bug

- mooncake-transfer-engine/src/transfer_metadata.cpp
Fixes incorrect initialization sequence in `startHandshakeDaemon()` by moving the daemon start call after callback registrations.
- Before: Daemon started before registering callbacks
- After: Callbacks registered first, then daemon started
The original order could cause race conditions where the daemon becomes active before callbacks are properly set up, potentially leading to missed or improperly handled handshake events.
> Fix Handshake Daemon Initialization Order

- mooncake-transfer-engine/src/transport/rdma_transport/endpoint_store.cpp
Currently, this project uses a SIEVE cache eviction algorithm for the RDMA endpoint store. However, this algorithm was originally designed for web caching, under the assumption that most newly inserted elements are cold. Therefore, it employs a "quick demotion" strategy that aggressively evicts newly inserted elements unless they have been visited again.
In the context of RDMA endpoints, however, we can assume that a newly inserted endpoint is likely to be used soon, otherwise there is no need to create it. Thus, we can set the default "visited" field of a newly inserted element to True, giving it a second chance.
In this way, the SIEVE algorithm essentially falls back to the CLOCK eviction algorithm. More advanced alternatives—such as LRU (less scalable due to high metadata maintenance …
> [TransferEngine] Fix SIEVE eviction algorithm for RDMA endpoint store

- mooncake-transfer-engine/src/transport/rdma_transport/rdma_transport.cpp
Pre-select device for entire transfer request to eliminate per-slice selection overhead while maintaining full backward compatibility.
- Pre-selection: Select device once per request instead of per slice
- Early validation: Validate device availability upfront to avoid late failures
- Reduced overhead: Reduces device selection calls **from O(n) to O(1)** per request, which is especially important when memory region fragmentation is severe.
- 100% backward compatible: Falls back to original logic when pre-selection fails
- No API changes: All existing interfaces remain unchanged
- No behavioral changes: Same error handling and retry mechanisms preserved
> [TE][RDMA Transport]: Simplify Transfer Submission Logic

- .github/workflows/release.yaml
- scripts/build_wheel.sh
Hello! From the release log in your actions, Python 3.8 was failed due to 
```
ValueError: Cannot repair wheel, because required library "libcuda.so.1" could not be located
```
After investigation, I believed that this was due to python 3.8 do not have auditwheels that capable of `--exclude` shared libraries with wildcards. You can refer to the PR https://github.com/pypa/auditwheel/pull/508#issue-2450955901 here.
It can be seen that Release for 6.2.0 is only suitable for python>=3.9.
And in your log, your auditwheel has a version of 6.1.0 in python 3.8 which does not support wild-card.
It can be seen that all  jobs have done except publish to PYPI. And it seems working well!
> [CI] Fix Release build_wheel.sh to make python 3.8 auditwheel happy

- mooncake-store/src/utils.cpp
otherwise, port assignments could collide.
> refactor(AutoPortBinder): remove SO_REUSEADDR setting

- mooncake-p2p-store/src/p2pstore/transfer_engine.go
when install tcp transport, nicPriorityMatrix is "". set args[0] to nil so that tcp transport can be installed
> [p2pstore] allow topologyMatrix to be empty

- mooncake-transfer-engine/example/transfer_engine_validator.cpp
This eliminates the warning:
```
Mooncake/mooncake-transfer-engine/example/transfer_engine_validator.cpp: In function ‘mooncake::Status initiatorWorker(mooncake::TransferEngine*, mooncake::SegmentID, int, void*)’:
Mooncake/mooncake-transfer-engine/example/transfer_engine_validator.cpp:309:29: warning: variable ‘opcode’ set but not used [-Wunused-but-set-variable]
309 |     TransferRequest::OpCode opcode;
```
> [Chores] Remove Unused Variable

- doc/en/transfer-engine.md
- doc/zh/transfer-engine.md
- mooncake-transfer-engine/include/config.h
- mooncake-transfer-engine/src/config.cpp
- mooncake-transfer-engine/src/transfer_metadata_plugin.cpp
Some servers restrict the allowed port range. It is better not to hardcode the PRC port range.
> Allow customizing RPC port range

- mooncake-store/tests/client_integration_test.cpp
This PR fixes the memory leak in client_integration_test.cpp caused by not freeing allocated segments.
> fix(store): fix memory leak in client_integration_test.cpp

- docs/source/getting_started/examples/vllm-integration/vllmv1-lmcache-integration.md
- docs/source/getting_started/quick-start.md
Based on the latest release and feedback from issue https://github.com/kvcache-ai/Mooncake/issues/878, we need to update the quick-start guide for Mooncake Store and the documentation for Mooncake + LMCache + vLLM v1.
cc @xiaguan
> [Docs] Update quick start and usage examples

- mooncake-store/src/master_service.cpp
The previous error logs were confusing users, so we've changed the fs LOG to INFO.
> fix(store): disable persistence instead of returning error

- mooncake-store/src/client.cpp
Include RPC time when calculating QueryResult lease timeout to make sure we are not getting corrupted data.
> [Store]: Get start_time before calling RPC in BatchQuery

- .devcontainer/Dockerfile
- CMakeLists.txt
- dependencies.sh
- mooncake-store/src/CMakeLists.txt
With more tests and analysis, we found that the root cause of #834 is serious memory fragmentation.
Insertion and deletion of metadata in Mooncake Master are accompanied by allocation and deallocation of small memory objects (typically hundreds of bytes). With large amount of metadata being inserted and removed, the memory space of Master gets seriously fragmented, resulting in unexpected memory consumption.
Using a more modern memory allocator (i.e. [jemalloc](https://jemalloc.net/)) can effectively alleviate this problem. Here is a comparision between the default libc allocator and jemalloc:
Test script:
```bash
#!/bin/bash
output_file=$1
top -b -n 1 -w 512 | grep mooncake_master >> $output_file
for ((i=0; i<10; i++)); do
python3 mooncake-store/tests/stress_cluster_benchmark.py \ …
```
> [Store]: Add option to use jemalloc in mooncake store master
