kvcache-ai/Mooncake

- doc/en/transfer-engine.md
- doc/zh/transfer-engine.md
- mooncake-transfer-engine/rust/Cargo.lock
- mooncake-transfer-engine/rust/Cargo.toml
- mooncake-transfer-engine/rust/build.rs
- mooncake-transfer-engine/rust/src/transfer_engine.rs
1. Update the package dependent on atty
2. Fix incorrect compilation dependency path
> fix: remove atty and fix dependency path

- CONTRIBUTING.md
fix minor typos in contributing.md
> [Doc] Fix typos in contributing.md

- mooncake-transfer-engine/example/transfer_engine_bench.cpp
- mooncake-transfer-engine/include/transport/cxl_transport/cxl_transport.h
- mooncake-transfer-engine/include/transport/nvmeof_transport/nvmeof_transport.h
- mooncake-transfer-engine/src/transport/nvmeof_transport/nvmeof_transport.cpp
- mooncake-transfer-engine/tests/tcp_transport_test.cpp
fix the build errors while enable USE_CUDA. same env as #18
> [Bugfix] build error when USE_CUDA

- doc/en/vllm-integration-v0.2.md
Since PR#51 has been merged, we need to change the metadata_server config guide of the vllm integration doc.
> Update metadata_server config info for vllm integration doc.

- .github/workflows/build-linux.yml
- CMakeLists.txt
- dependencies.sh
- mooncake-transfer-engine/include/multi_transport.h
- mooncake-transfer-engine/src/multi_transport.cpp
- mooncake-transfer-engine/src/transfer_metadata_plugin.cpp
- mooncake-transfer-engine/tests/CMakeLists.txt
- mooncake-transfer-engine/tests/tcp_transport_test.cpp
- mooncake-transfer-engine/tests/transfer_metadata_test.cpp
also fix Transport leaking in `MultiTransport::transport_map_`.
> [TransferEngine] test: cmake enable testing.

- dependencies.sh
Fix the invalid go release url in dependencies.sh
> fix invalid go release url

- .devcontainer/Dockerfile
- .devcontainer/README.md
- .devcontainer/devcontainer.json
make it easier to develop transfer engine for vscode users.
> [Build] feature: add dev container.

- mooncake-transfer-engine/src/topology.cpp
In container, we might just mount part of ubvers into the pod, i.e.
```
$ ls /sys/class/infiniband
erdma_0  erdma_1
$ ls /dev/infiniband/
rdma_cm  uverbs0
$ ibv_devices
device                 node GUID
------              ----------------
erdma_0             02163efffe1041ea
```
> [TransferEngine] fix: use ibv_get_device_list to get the IB devices.

- mooncake-transfer-engine/src/transport/rdma_transport/worker_pool.cpp
Transfer engine uses memcpy to make local transfer faster, but the previous implementation ignores the opcode so that the direction may be wrong.
> fix: memcpy direction wrong for read operations

- doc/en/build.md
- doc/zh/build.md
- mooncake-transfer-engine/CMakeLists.txt
- mooncake-transfer-engine/include/CMakeLists.txt
- mooncake-transfer-engine/src/CMakeLists.txt
Make people easier to use transfer engine as a library.
> [TransferEngine] Build: build/install shared object for transfer engine.

- doc/zh/troubleshooting.md
- mooncake-transfer-engine/src/transport/rdma_transport/rdma_endpoint.cpp
> [TransferEngine] Correct the Typo

- CMakeLists.txt
- mooncake-transfer-engine/src/transfer_metadata.cpp
- mooncake-transfer-engine/src/transport/tcp_transport/CMakeLists.txt
> [TransferEngine] Fix typos

- mooncake-integration/vllm/vllm_adaptor.cpp
- mooncake-integration/vllm/vllm_adaptor.h
Enhance the API of VLLM adapter
> Extend VLLMAdaptor API

- dependencies.sh
> [CI] Update etcd-cpp CMake policy version in dependencies script

- README.md
- mooncake-transfer-engine/include/transport/transport.h
- mooncake-transfer-engine/src/transfer_metadata_plugin.cpp
- mooncake-transfer-engine/src/transport/nvmeof_transport/nvmeof_transport.cpp
- mooncake-transfer-engine/src/transport/rdma_transport/rdma_transport.cpp
- mooncake-transfer-engine/src/transport/tcp_transport/tcp_transport.cpp
- mooncake-transfer-engine/src/transport/transport.cpp
This PR aims to fix problems mentioned in #221.
> [FIX] reduce performance overhead from allocating slices

- mooncake-transfer-engine/src/transfer_engine.cpp
This patch fixes problem in #225. In particular, we add a environment variable `MC_TCP_BIND_ADDRESS` to specify the local bind addresses rather than selecting the first one, with port randomly-assigned.
> [FIX] bind failure from legacy RPC_PORT_BINDING

- mooncake-transfer-engine/src/transfer_metadata_plugin.cpp
When compiled with -DUSE_REDIS=ON, the metadata plugin will use Redis as the default storage method. However, hiredis (introduced in `transfer_metadata_plugin.cpp`) is not thread-safe. 
This change adds a lock to prevent errors (which we have actually encountered in our scenario) during multi-threaded runtime.
> [Bugfix]: fix redis access error during multi-threaded runtime.

- mooncake-transfer-engine/include/transport/nvmeof_transport/nvmeof_transport.h
- mooncake-transfer-engine/include/transport/transport.h
- mooncake-transfer-engine/src/transport/nvmeof_transport/nvmeof_transport.cpp
ref to [issue 253](https://github.com/kvcache-ai/Mooncake/issues/253)
> Fix nvmeof build issue

- mooncake-transfer-engine/include/transfer_engine.h
- mooncake-transfer-engine/include/transfer_engine_c.h
- mooncake-transfer-engine/src/transfer_engine.cpp
- mooncake-transfer-engine/src/transfer_engine_c.cpp
This is needed by NIXL integration
> [TransferEngine] add get local ip and port api

- mooncake-transfer-engine/include/common.h
- mooncake-transfer-engine/src/transfer_metadata_plugin.cpp
- mooncake-transfer-engine/src/transport/rdma_transport/rdma_endpoint.cpp
also fix invalid data length in writeString.
> [TransferEngine] make sure tcp connection close gracefully.

- mooncake-transfer-engine/include/transfer_engine.h
- mooncake-transfer-engine/include/transfer_engine_c.h
- mooncake-transfer-engine/include/transfer_metadata.h
- mooncake-transfer-engine/src/transfer_engine.cpp
- mooncake-transfer-engine/src/transfer_engine_c.cpp
- mooncake-transfer-engine/src/transfer_metadata.cpp
- mooncake-transfer-engine/tests/transfer_metadata_test.cpp
According to suggestions from @eryugey , we provide a new interface to close segment.
> [TransferEngine] implement close segment by name

- mooncake-integration/transfer_engine/transfer_engine_py.cpp
- mooncake-integration/transfer_engine/transfer_engine_py.h
Add transfer submit and check status api to unblock CPU.
> [TransferEngine] Add async transfer submit and check status api

- .devcontainer/Dockerfile
- mooncake-transfer-engine/src/transport/rdma_transport/rdma_context.cpp
otherwise, memory leaking will happen in `waiting_list_`.
also fix a bit for dev container.
> [Transfer Engine]: make reclaimEndpoint got chance to run.

- doc/zh/vllm-integration-v1.md
This PR added Chinese translation for the latest documentation.
Additionally, I've noticed some formatting inconsistencies in current markdown docuements, including indentation issues in code blocks and inconsistent line breaks between paragraphs. If needed, I can submit a new PR to improve these formatting improvements.
> [Doc] Add Chinese translation for vllm-integration-v1.md

- mooncake-integration/store/store_py.cpp
- mooncake-integration/store/store_py.h
- mooncake-integration/vllm/distributed_object_store.cpp
- mooncake-integration/vllm/distributed_object_store.h
- mooncake-integration/vllm/vllm_adaptor.cpp
- mooncake-store/include/client.h
- mooncake-store/include/master_client.h
- mooncake-store/include/master_metric_manager.h
- mooncake-store/include/master_service.h
- mooncake-store/include/rpc_service.h
- mooncake-store/src/client.cpp
- mooncake-store/src/master.cpp
- mooncake-store/src/master_client.cpp
- mooncake-store/src/master_metric_manager.cpp
- mooncake-store/src/master_service.cpp
- mooncake-store/tests/master_service_test.cpp
This supply an API to remove all keys, so that we can execute some integration test again without the previous state.
- For easy to test, I wrote a `mooncake_store_service.py` for start a store with rest api.
```python
#!/usr/bin/env python3
import argparse
import asyncio
import json
import logging
import os
from aiohttp import web
from mooncake.store import MooncakeDistributedStore
class MooncakeStoreConfig:
def __init__(self, local_hostname: str, metadata_server: str, 
global_segment_size: int = 3355443200,
local_buffer_size: int = 1073741824,
protocol: str = "tcp",
device_name: str = "",
master_server_address: str = ""):
self.local_hostname = local_hostname
self.metadata_server = metadata_server
self.global_segment_size = global_segment_size
self.local_buffer_size = local_buffer_size …
```
> [Store] Improve: Add RemoveAll rpc for remove all keys

- README.md
News in the README.md will be updated.
> [DOC] Add news about NIXL supports Mooncake as a backend

- mooncake-store/include/allocation_strategy.h
In buffer allocation, when there are multiple eligible allocators, it will randomly select one and use it to try to allocate the buffer. This process will iterate many times, but each time the program will only try a specific one, instead of trying other eligible allocators. This pr fixex this issue.
> [BugFix] Buffer Allocation Always Tries on the Same Allocator

- mooncake-wheel/pyproject.toml
It includes some small improvements and a few bug fixes.
> chore: bump version to 0.3.1 in pyproject.toml

- mooncake-transfer-engine/example/memory_pool.cpp
- mooncake-transfer-engine/example/transfer_engine_bench.cpp
- mooncake-transfer-engine/example/transfer_engine_bench_with_retry.cpp
- mooncake-transfer-engine/include/common.h
- mooncake-transfer-engine/tests/nvmeof_transport_test.cpp
- mooncake-transfer-engine/tests/rdma_transport_test.cpp
- mooncake-transfer-engine/tests/rdma_transport_test2.cpp
Add function `getHostName` into common.h
> [TransferEngine] Reduce duplicated code

- mooncake-store/src/master_service.cpp
This change can reduce iterate the key of shard as less as possible. 
This change has been discussed offline with @ykwd and really appreciate with the help and suggestion!
> Improve the batchEvict logic

- doc/en/lmcacheV1-deployment.md
1. file vllm/examples/lmcache/disagg_prefill_lmcache_v1/disagg_vllm_launcher.sh has been moved to vllm/examples/others/lmcache/disagg_prefill_lmcache_v1/disagg_vllm_launcher.sh
2. typo for IP_of_Machine_A
> [Doc] Update lmcacheV1-deployment.md

- mooncake-p2p-store/build.sh
> [P2P Store] Add cuda link option when it is installed

- CMakeLists.txt
- mooncake-common/FindGLOG.cmake
- mooncake-common/FindJsonCpp.cmake
- mooncake-common/common.cmake
- mooncake-transfer-engine/CMakeLists.txt
- mooncake-transfer-engine/include/transfer_metadata.h
- mooncake-transfer-engine/src/CMakeLists.txt
> [cmake]fix cmake for centos

- doc/en/mooncake-store-preview.md
- doc/zh/mooncake-store-preview.md
- docs/source/design/mooncake-store-preview.md
The high availability mode has now been partially completed and passed testing, so it can be included in the documentation.
> [DOC] Add Description for High Availability in Store

- doc/en/mooncake-store-preview.md
- doc/zh/mooncake-store-preview.md
- docs/source/design/mooncake-store-preview.md
Add Description for Data Persistence and KVCache offloading in Store.Edit consistency description in Key features.
> [DOC]: Add Description for Data Persistence and KVCache offloading in Store

- mooncake-transfer-engine/src/topology.cpp
The function `getPciDistance` is used to determine the PCIe topological distance between two devices (e.g., GPU and NIC) by comparing their sysfs paths. Previously, the function only returned 0 if the two devices had exactly the same sysfs path prefix, i.e., their paths were identical except for the device itself. This approach failed to recognize that two devices under the same PCIe switch/root port, but with different device IDs, should also be considered as having a distance of 0.
Suppose we have two PCIe devices with the following bus IDs and sysfs paths:
- bus1: `0000:bc:00.0`, path1: `/sys/devices/pci0000:b2/0000:b2:03.1/0000:b9:00.0/0000:ba:01.0/0000:bc:00.0`
- bus2: `0000:bb:00.0`, path2: `/sys/devices/pci0000:b2/0000:b2:03.1/0000:b9:00.0/0000:ba:00.0/0000:bb:00.0`
In this case, …
> feat(topology): improve HCA selection by considering PCIe distance

- doc/en/lmdeploy-integration-v0.9.md
- docs/source/getting_started/examples/lmdeploy-integration-v0.9.md
- docs/source/index.md
This pr explains how we integrate LMDeploy with Mooncake transfer engine to achieve PD disaggregation. The reference PR is https://github.com/InternLM/lmdeploy/pull/3620#issue-3127177213
> docs: add support for LMDeploy

- mooncake-store/include/rpc_service.h
> [Mooncake Store] perf: avoid memory copy for rpc service

- mooncake-transfer-engine/include/transfer_metadata.h
- mooncake-transfer-engine/include/transport/tcp_transport/tcp_transport.h
- mooncake-transfer-engine/src/transfer_metadata.cpp
- mooncake-transfer-engine/src/transfer_metadata_plugin.cpp
- mooncake-transfer-engine/src/transport/rdma_transport/worker_pool.cpp
- mooncake-transfer-engine/src/transport/tcp_transport/tcp_transport.cpp
> [TransferEngine] Fix address already in use

- mooncake-integration/store/store_py.cpp
- mooncake-integration/store/store_py.h
Address this issue: https://github.com/kvcache-ai/Mooncake/issues/640
> [Fix] Support large global segment

- mooncake-integration/CMakeLists.txt
- mooncake-integration/integration_utils.h
- mooncake-integration/store/store_py.cpp
Move utils to a new header in mooncake integration & add new quant data types (fp16, fp8, e5m2)
> [Store][bind] add new support data types

- mooncake-common/etcd/etcd_wrapper.go
This PR enables client-side HA for Transfer Engine by allowing multiple etcd endpoints in the metadata plugin (comma or semicolon separated). Store Master already supports multi-endpoint etcd but clients did not. This code is normalize and pass the endpoint list to the etcd v3 client, enabling proper failover
> [Store] Add multi-endpoint etcd support for Transfer Engine metadata plugin

- mooncake-transfer-engine/include/transfer_engine.h
- mooncake-transfer-engine/include/transport/rdma_transport/endpoint_store.h
- mooncake-transfer-engine/include/transport/rdma_transport/rdma_context.h
- mooncake-transfer-engine/include/transport/rdma_transport/rdma_endpoint.h
- mooncake-transfer-engine/src/transport/rdma_transport/endpoint_store.cpp
- mooncake-transfer-engine/src/transport/rdma_transport/rdma_context.cpp
- mooncake-transfer-engine/src/transport/rdma_transport/rdma_endpoint.cpp
TODO: mooncake client support totoal QP calculation. Master gathers QP info from all clients.
> [Transfer Engine] Metrics: Add total qp metrics

- doc/en/mooncake-store-preview.md
- doc/zh/mooncake-store-preview.md
- docs/source/design/mooncake-store-preview.md
- docs/source/mooncake-store-api/python-binding.md
- mooncake-store/include/client.h
- mooncake-store/include/master_client.h
- mooncake-store/include/master_service.h
- mooncake-store/include/storage_backend.h
see [734](https://github.com/kvcache-ai/Mooncake/pull/734)
> [Doc] update doc for *Regex interface

- CONTRIBUTING.md
Add description for CONTRIBUTING.md
> [Doc] Add description for CONTRIBUTING.md

- mooncake-integration/store/store_py.cpp
Fix https://github.com/kvcache-ai/Mooncake/issues/782
> GIL release for put_tensor and get_tenor

- mooncake-integration/store/store_py.cpp
Fix https://github.com/kvcache-ai/Mooncake/issues/802
> [Store] Remove unnecessary register buffer from put_tensor

- mooncake-store/src/storage_backend.cpp
- mooncake-store/src/transfer_task.cpp
> [Store] skip null buffer

- mooncake-transfer-engine/include/transfer_engine.h
> [Transfer Engine] Post notify if all transfer tasks are completed

- mooncake-integration/CMakeLists.txt
- mooncake-wheel/mooncake/README.md
- mooncake-wheel/mooncake/mooncake_connector_v1.py
- mooncake-wheel/mooncake/vllm_v1_proxy_server.py
Group contiguous block ids.
Add expired time for P node.
Copy proxy server from vllm repo.
> [Misc] improvements for mooncake_connector_v1
